# Generated by Django 3.0.4 on 2020-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wplyw',
            name='category',
            field=models.CharField(choices=[('AS', 'AS'), ('UB', 'UB'), ('RA', 'RA')], default='AS', max_length=2),
        ),
        migrations.AddField(
            model_name='wplyw',
            name='inflow',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wplyw',
            name='outflow',
            field=models.CharField(default='', max_length=128),
        ),
    ]
