# Generated by Django 3.0.4 on 2020-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200312_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='wplyw',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
