# Generated by Django 3.0.4 on 2020-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wplyw_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wplyw',
            name='date',
        ),
        migrations.AddField(
            model_name='wplyw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
