# Generated by Django 3.0.4 on 2020-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200312_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wplyw',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
