# Generated by Django 3.0.4 on 2020-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200312_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wplyw',
            name='category',
            field=models.CharField(choices=[('AS', 'AS'), ('UB', 'UB'), ('RACHUNEK', 'RA')], default='AS', max_length=8),
        ),
    ]
