# Generated by Django 3.0.4 on 2020-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200313_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wplyw',
            name='category',
            field=models.CharField(choices=[('Artykuły spożywcze', 'AS'), ('Ubrania', 'UB'), ('Rachunek', 'RA')], default='AS', max_length=18),
        ),
    ]
