# Generated by Django 3.0.4 on 2020-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200313_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wplyw',
            name='inflow',
        ),
        migrations.RemoveField(
            model_name='wplyw',
            name='outflow',
        ),
        migrations.AddField(
            model_name='wplyw',
            name='flow',
            field=models.CharField(choices=[('Wpływ', 'Wpływ'), ('Rozchód', 'Rozchód')], default='Wybierz', max_length=10),
        ),
        migrations.AddField(
            model_name='wplyw',
            name='how_much',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9999),
        ),
    ]
